### ISSUE TITLE
Update Pydantic to v2

### ISSUE THREAD

**Issue by dbluhm** [Indicio-tech/pydid#64]
Pydantic v2 was recently released with some exciting improvements:
- 5-50x faster
- Better handling of custom serialization
- Cleaner validators (and fewer magical keyword arguments)

Pydantic v2 requires Python >= 3.7 so this will have to wait until after we drop support for python 3.6.

**Comment by bit-sbonzelet** [comment]
Hi

is there a roadmap or any plan to upgrade?

**Comment by dbluhm** [comment]
Some work was started by @ff137 in #72 but it has not been pushed through to completion yet. This isn't currently high on my priority list but I'd be happy to review contributions.

**Comment by ff137** [comment]
I can try tackle this one again - previously hit a roadblock with some nested methods not serialising properly, and haven't tried again! 

Will probably need a few days, but I'll get around to it 👌

**Comment by ff137** [comment]
By the way, #72 is ready for review :-) 
I tested it in a ACA-Py pull request and everything passed: https://github.com/hyperledger/aries-cloudagent-python/pull/2919
