### ISSUE TITLE
Upgrade `typing-extensions`

### ISSUE THREAD

**Issue by ff137** [Indicio-tech/pydid#68]
Good day

I notice the following constraint for `typing-extensions` in the `pyproject.toml`:
```
typing-extensions = ">=4.0.0,<4.1.0"
```

Is there a specific reason for requiring <4.1.0?

I'd be happy to help make the changes to get it compatible with the latest (4.7.1), if possible

**Comment by dbluhm** [comment]
Addressed in #69
